# Generated by Django 3.2.6 on 2022-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='creditscore',
            field=models.FloatField(default=None, null=True),
        ),
    ]
